version: "3.9"

services:

  db:
    image: postgres:16
    container_name: fleet_postgres
    restart: always

    environment:
      POSTGRES_USER: fleet_user
      POSTGRES_PASSWORD: fleet_password
      POSTGRES_DB: fleet_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: fleet_backend

    restart: always

    ports:
      - "8000:8000"

    volumes:
      - ./backend:/app

    depends_on:
      - db

    env_file:
      - ./backend/.env

volumes:
  postgres_data:
