"""vehicle maintenance

Revision ID: 93567b0ca727
Revises: 069b58ec8d9b
Create Date: 2026-06-22 12:46:58.962899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '93567b0ca727'
down_revision: Union[str, Sequence[str], None] = '069b58ec8d9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicle_assignments_company_id'), table_name='vehicle_assignments')
    op.drop_index(op.f('ix_vehicle_assignments_driver_id'), table_name='vehicle_assignments')
    op.drop_index(op.f('ix_vehicle_assignments_id'), table_name='vehicle_assignments')
    op.drop_index(op.f('ix_vehicle_assignments_is_active'), table_name='vehicle_assignments')
    op.drop_index(op.f('ix_vehicle_assignments_vehicle_id'), table_name='vehicle_assignments')
    op.drop_index(op.f('ix_vehicle_driver_active'), table_name='vehicle_assignments')
    op.drop_table('vehicle_assignments')
    op.drop_index(op.f('ix_drivers_id'), table_name='drivers')
    op.drop_table('drivers')
    op.add_column('vehicles', sa.Column('last_service_km', sa.Integer(), nullable=True))
    op.add_column('vehicles', sa.Column('last_service_date', sa.DateTime(), nullable=True))
    op.add_column('vehicles', sa.Column('next_service_km', sa.Integer(), nullable=True))
    op.add_column('vehicles', sa.Column('next_inspection_date', sa.Date(), nullable=True))
    op.add_column('vehicles', sa.Column('next_insurance_date', sa.Date(), nullable=True))
    op.alter_column('vehicles', 'brand',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('vehicles', 'model',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('vehicles', 'fuel_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_vehicles_transmission'), 'vehicles', ['transmission'], unique=False)
    op.drop_column('vehicles', 'engine')
    op.drop_column('vehicles', 'engine_capacity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('engine_capacity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('vehicles', sa.Column('engine', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_vehicles_transmission'), table_name='vehicles')
    op.alter_column('vehicles', 'fuel_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('vehicles', 'model',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('vehicles', 'brand',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('vehicles', 'next_insurance_date')
    op.drop_column('vehicles', 'next_inspection_date')
    op.drop_column('vehicles', 'next_service_km')
    op.drop_column('vehicles', 'last_service_date')
    op.drop_column('vehicles', 'last_service_km')
    op.create_table('drivers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('license_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('drivers_company_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('drivers_pkey'))
    )
    op.create_index(op.f('ix_drivers_id'), 'drivers', ['id'], unique=False)
    op.create_table('vehicle_assignments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('vehicle_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('driver_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('assigned_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('unassigned_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('vehicle_assignments_company_id_fkey')),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], name=op.f('vehicle_assignments_driver_id_fkey')),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('vehicle_assignments_vehicle_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('vehicle_assignments_pkey'))
    )
    op.create_index(op.f('ix_vehicle_driver_active'), 'vehicle_assignments', ['vehicle_id', 'driver_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_vehicle_assignments_vehicle_id'), 'vehicle_assignments', ['vehicle_id'], unique=False)
    op.create_index(op.f('ix_vehicle_assignments_is_active'), 'vehicle_assignments', ['is_active'], unique=False)
    op.create_index(op.f('ix_vehicle_assignments_id'), 'vehicle_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_vehicle_assignments_driver_id'), 'vehicle_assignments', ['driver_id'], unique=False)
    op.create_index(op.f('ix_vehicle_assignments_company_id'), 'vehicle_assignments', ['company_id'], unique=False)
    # ### end Alembic commands ###
