"""baseline

Revision ID: e9ef777b7d0b
Revises: 
Create Date: 2026-06-25 11:48:14.187555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9ef777b7d0b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_table('maintenance_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('interval_km', sa.Integer(), nullable=False),
    sa.Column('warning_before_km', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_maintenance_rule_company_name', 'maintenance_rules', ['company_id', 'name'], unique=False)
    op.create_index(op.f('ix_maintenance_rules_company_id'), 'maintenance_rules', ['company_id'], unique=False)
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('license_number', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drivers_id'), 'drivers', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('plate_number', sa.String(), nullable=False),
    sa.Column('vin_number', sa.String(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('mileage', sa.Integer(), nullable=True),
    sa.Column('fuel_type', sa.String(), nullable=False),
    sa.Column('transmission', sa.String(), nullable=True),
    sa.Column('registration_date', sa.Date(), nullable=True),
    sa.Column('insurance_expiry_date', sa.Date(), nullable=True),
    sa.Column('technical_inspection_expiry_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('last_service_km', sa.Integer(), nullable=True),
    sa.Column('last_service_date', sa.DateTime(), nullable=True),
    sa.Column('next_service_km', sa.Integer(), nullable=True),
    sa.Column('next_inspection_date', sa.Date(), nullable=True),
    sa.Column('next_insurance_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vehicle_company_plate', 'vehicles', ['company_id', 'plate_number'], unique=False)
    op.create_index(op.f('ix_vehicles_company_id'), 'vehicles', ['company_id'], unique=False)
    op.create_index(op.f('ix_vehicles_id'), 'vehicles', ['id'], unique=False)
    op.create_index(op.f('ix_vehicles_plate_number'), 'vehicles', ['plate_number'], unique=True)
    op.create_index(op.f('ix_vehicles_status'), 'vehicles', ['status'], unique=False)
    op.create_index(op.f('ix_vehicles_transmission'), 'vehicles', ['transmission'], unique=False)
    op.create_index(op.f('ix_vehicles_vin_number'), 'vehicles', ['vin_number'], unique=True)
    op.create_table('maintenance_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('rule_name', sa.String(), nullable=False),
    sa.Column('due_km', sa.Integer(), nullable=False),
    sa.Column('current_km', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alert_company_resolved', 'maintenance_alerts', ['company_id', 'resolved'], unique=False)
    op.create_index(op.f('ix_maintenance_alerts_company_id'), 'maintenance_alerts', ['company_id'], unique=False)
    op.create_index(op.f('ix_maintenance_alerts_resolved'), 'maintenance_alerts', ['resolved'], unique=False)
    op.create_index(op.f('ix_maintenance_alerts_vehicle_id'), 'maintenance_alerts', ['vehicle_id'], unique=False)
    op.create_table('vehicle_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('unassigned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_va_active', 'vehicle_assignments', ['is_active'], unique=False)
    op.create_index('ix_va_company', 'vehicle_assignments', ['company_id'], unique=False)
    op.create_index('ix_va_company_vehicle_active', 'vehicle_assignments', ['company_id', 'vehicle_id', 'is_active'], unique=False)
    op.create_index('ix_va_driver', 'vehicle_assignments', ['driver_id'], unique=False)
    op.create_index('ix_va_vehicle', 'vehicle_assignments', ['vehicle_id'], unique=False)
    op.create_index('ix_va_vehicle_date', 'vehicle_assignments', ['vehicle_id', 'assigned_at'], unique=False)
    op.create_index(op.f('ix_vehicle_assignments_company_id'), 'vehicle_assignments', ['company_id'], unique=False)
    op.create_index(op.f('ix_vehicle_assignments_driver_id'), 'vehicle_assignments', ['driver_id'], unique=False)
    op.create_index(op.f('ix_vehicle_assignments_is_active'), 'vehicle_assignments', ['is_active'], unique=False)
    op.create_index(op.f('ix_vehicle_assignments_vehicle_id'), 'vehicle_assignments', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicle_assignments_vehicle_id'), table_name='vehicle_assignments')
    op.drop_index(op.f('ix_vehicle_assignments_is_active'), table_name='vehicle_assignments')
    op.drop_index(op.f('ix_vehicle_assignments_driver_id'), table_name='vehicle_assignments')
    op.drop_index(op.f('ix_vehicle_assignments_company_id'), table_name='vehicle_assignments')
    op.drop_index('ix_va_vehicle_date', table_name='vehicle_assignments')
    op.drop_index('ix_va_vehicle', table_name='vehicle_assignments')
    op.drop_index('ix_va_driver', table_name='vehicle_assignments')
    op.drop_index('ix_va_company_vehicle_active', table_name='vehicle_assignments')
    op.drop_index('ix_va_company', table_name='vehicle_assignments')
    op.drop_index('ix_va_active', table_name='vehicle_assignments')
    op.drop_table('vehicle_assignments')
    op.drop_index(op.f('ix_maintenance_alerts_vehicle_id'), table_name='maintenance_alerts')
    op.drop_index(op.f('ix_maintenance_alerts_resolved'), table_name='maintenance_alerts')
    op.drop_index(op.f('ix_maintenance_alerts_company_id'), table_name='maintenance_alerts')
    op.drop_index('ix_alert_company_resolved', table_name='maintenance_alerts')
    op.drop_table('maintenance_alerts')
    op.drop_index(op.f('ix_vehicles_vin_number'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_transmission'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_status'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_plate_number'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_company_id'), table_name='vehicles')
    op.drop_index('ix_vehicle_company_plate', table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_drivers_id'), table_name='drivers')
    op.drop_table('drivers')
    op.drop_index(op.f('ix_maintenance_rules_company_id'), table_name='maintenance_rules')
    op.drop_index('ix_maintenance_rule_company_name', table_name='maintenance_rules')
    op.drop_table('maintenance_rules')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
